132 migrate away from jest
fastify/fastify-awilix pull request #134
Opened 2024-04-19 11:54 UTC by puskin94

Closes https://github.com/fastify/fastify-awilix/issues/132

2024-04-19 11:58 UTC, gurgunday commented
c8 is what we (and tap) use, thank you for this PR!

2024-04-19 11:59 UTC, gurgunday commented
Just make sure to target `next`

https://github.com/fastify/fastify-awilix/tree/next

2024-04-19 12:03 UTC, puskin94 commented
> Just make sure to target `next`
> 
> https://github.com/fastify/fastify-awilix/tree/next

uh, nice catch! just updated. 

Targetting node 18 now, should we skip the jobs for node 14 an 16, being failing?

2024-04-19 12:04 UTC, gurgunday commented
> Targetting node 18 now, should we skip the jobs for node 14 an 16, being failing?

Yes, it will test for node >=18 in `next`, as soon as the conflicts are resolved

2024-04-19 12:11 UTC, puskin94 commented
> > Targetting node 18 now, should we skip the jobs for node 14 an 16, being failing?
> 
> Yes, it will test for node >=18 in `next`, as soon as the conflicts are resolved

Yeah, that was my bad :)

Should be fixed now!

2024-04-19 13:43 UTC, simoneb approved these changes
LGTM

2024-04-19 13:51 UTC, Fdawgs requested changes

2024-04-19 13:51 UTC, Fdawgs commented on package.json
> +    "test:coverage": "c8 --100 npm run test",
Please move this line back, the `test:` scripts were sorted alphabetically.

2024-04-19 14:39 UTC, marco-ippolito approved these changes

2024-04-19 14:45 UTC, Fdawgs approved these changes

2024-04-20 09:14 UTC, gurgunday commented on package.json
> +    "test": "node --test",
Coverage should be enabled by default as is already the case with `tap@18` in other repos

2024-04-20 09:14 UTC, gurgunday commented on package.json
> +    "test": "node --test",
The CI only runs `npm run test` so currently it doesn't check coverage

2024-04-20 09:15 UTC, gurgunday commented on package.json
> +    "test": "node --test",
```suggestion
    "test": "c8 node --test",
```

2024-04-20 09:16 UTC, gurgunday commented on package.json
> +    "test:coverage": "c8 --100 npm run test",
I think you can delete this after https://github.com/fastify/fastify-awilix/pull/134/files#r1573219656

2024-04-20 13:00 UTC, gurgunday reviewed
Hopefully the last review ;)

You forgot the most important step, removing `jest`

https://github.com/fastify/fastify-awilix/blob/fd7bde2bd1ba2b8cde997725586af7ce2898a2b2/package.json#L40

2024-04-20 15:28 UTC, puskin94 commented
> Hopefully the last review ;)
> 
> You forgot the most important step, removing `jest`
> 
> https://github.com/fastify/fastify-awilix/blob/fd7bde2bd1ba2b8cde997725586af7ce2898a2b2/package.json#L40

oh boi, I didn't forget, it got reintroduced when I merged "next" into my branch!

Good catch, and thanks :)

2024-04-20 16:56 UTC, gurgunday approved these changes
lgtm

2024-04-20 16:57 UTC, merged

2024-04-20 16:58 UTC, gurgunday commented
Thank you!